<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e225b9c7-13e4-4b85-a339-13b942ae4d54</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="4.13.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../LawFirm.Application/LawFirm.Application.csproj" />
    <ProjectReference Include="../LawFirm.Infrastructure/LawFirm.Infrastructure.csproj" />
    <ProjectReference Include="../LawFirm.Shared/LawFirm.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers/" />
  </ItemGroup>

</Project>
